# Generated by Django 4.2 on 2023-06-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('narx', models.PositiveSmallIntegerField()),
                ('min_miqdor', models.IntegerField()),
                ('davlat', models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Russia', 'Russia'), ('Armenia', 'Armenia'), ('Tajikistan', 'Tajikistan'), ('Kazakhstan', 'Kazakhstan'), ('Kyrgzstan', 'Kyrgzstan'), ('Azerbayjan', 'Azerbayjan'), ('Moldova', 'Moldova'), ('Latviya', 'Latviya'), ('Turkmenistan', 'Turkmenistan')], max_length=50)),
                ('brend', models.CharField(max_length=70)),
                ('matn', models.CharField(max_length=200)),
                ('kafolat', models.CharField(default="Kafolat yo'q", max_length=20)),
                ('chegirma', models.PositiveSmallIntegerField(default=0)),
                ('rasm', models.FileField(upload_to='')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.bolim')),
            ],
        ),
    ]
