# Generated by Django 4.2 on 2023-06-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
