# Generated by Django 4.2 on 2023-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='mavjud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='yetkazish',
            field=models.IntegerField(default=0),
        ),
    ]
