# Generated by Django 4.2 on 2023-06-13 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
                ('shahar', models.CharField(max_length=60)),
                ('davlat', models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Russia', 'Russia'), ('Armenia', 'Armenia'), ('Tajikistan', 'Tajikistan'), ('Kazakhstan', 'Kazakhstan'), ('Kyrgzstan', 'Kyrgzstan'), ('Azerbayjan', 'Azerbayjan'), ('Moldova', 'Moldova'), ('Latviya', 'Latviya'), ('Turkmenistan', 'Turkmenistan')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Foydalanuvchi',
        ),
    ]
